In [1]:
import numpy as np
import pandas as p
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import colors
# from adjustText import adjust_text
from Bio import SeqIO
from Bio.Seq import Seq
%matplotlib inline

import gzip
from cyvcf2 import VCF

from itertools import combinations

sns.set_style('white')
sns.set_style('ticks')
sns.set_color_codes()

In [24]:
calledSNPs = p.read_csv('EvolvingFront_WGS_calledSNPs.tab',delimiter='\t',header=0)

In [38]:
sample_names = calledSNPs.columns[8:]

In [133]:




diffs = np.diff(calledSNPs['POS'].values)
close_locs = np.where((np.abs(diffs) < 2) & (np.abs(diffs)>0))



if len(close_locs) > 0:
    
    for loc in list(close_locs[0]):
        these_locs = [loc,loc+1]
        close_ones = calledSNPs[calledSNPs.index.isin(calledSNPs.index[these_locs])]
        sample_locs = np.where(np.isin(close_ones[sample_names].values, ['0|1','1|1']))
        if len(sample_locs[0]) > 0:
            print(sample_locs)
            print(close_ones[list(['CHROM','POS','REF','ALT','ANN[0].GENE','ANN[0].EFFECT'])+list(np.unique(sample_names[sample_locs[1]]))])
            
    
#     close_locs = list(close_locs[0])
#     print(close_locs)
#     additions = []
#     for i in close_locs:
# #         print(close_locs)
#         additions.append(i+1)
#     close_locs = np.unique(close_locs+additions)
# #     print(this_chrom[this_chrom.index.isin(this_chrom.index[close_locs])])
# #     break

# close_ones = calledSNPs[calledSNPs.index.isin(calledSNPs.index[close_locs])]
# locs = np.where(np.isin(close_ones[sample_names].values, ['0|1','1|1']))

(array([0, 1]), array([136, 136]))
   CHROM     POS REF ALT ANN[0].GENE     ANN[0].EFFECT  \
79    IV  569027   G   T    tD(GUC)D  missense_variant   
80    IV  569028   T   C    tD(GUC)D  missense_variant   

   EvolvingFront_WGS_Plate3_A10  
79                          1|1  
80                          1|1  
(array([0, 1]), array([172, 172]))
   CHROM     POS REF ALT ANN[0].GENE            ANN[0].EFFECT  \
93    IV  878372   A   G   YDR210W-A  downstream_gene_variant   
94    IV  878373   C   T   YDR210W-A  downstream_gene_variant   

   EvolvingFront_WGS_Plate3_D12  
93                          1|1  
94                          1|1  
(array([0, 0, 1, 1]), array([ 46, 332,  46, 332]))
    CHROM     POS REF ALT ANN[0].GENE          ANN[0].EFFECT  \
169    VI  143894   A   T        DEG1  upstream_gene_variant   
170    VI  143895   A   T        DEG1  upstream_gene_variant   

    EvolvingFront_WGS_Plate2_A02 EvolvingFront_WGS_Plate5_F03  
169                          0|1               

CHROM     POS REF ALT ANN[0].GENE            ANN[0].EFFECT  \
6       I   39837   T   C        GPB2       synonymous_variant   
7       I   39838   A  AT        GPB2       frameshift_variant   
79     IV  569027   G   T    tD(GUC)D         missense_variant   
80     IV  569028   T   C    tD(GUC)D         missense_variant   
93     IV  878372   A   G   YDR210W-A  downstream_gene_variant   
..    ...     ...  ..  ..         ...                      ...   
607   XVI  156322   A   C        PUS1    upstream_gene_variant   
608   XVI  156324   A   T        PUS1    upstream_gene_variant   
609   XVI  156325   A   T        PUS1    upstream_gene_variant   
610   XVI  156326   A   T        PUS1    upstream_gene_variant   
611   XVI  156328   G   T        PUS1    upstream_gene_variant   

    EvolvingFront_WGS_Plate1_A02 EvolvingFront_WGS_Plate2_A02  \
6                            0/0                          0/0   
7                            0/0                          0/0   
79                           0/0                          0/0   
80                           0/0                          0/0   
93                           0/0                          0/0   
..                           ...                          ...   
607                          0/0                          0/0   
608                          0/0                          0/0   
609                          0/0                          0/0   
610                          0/0                          0/0   
611                          0/0                          0/0   

    EvolvingFront_WGS_Plate2_E05 EvolvingFront_WGS_Plate3_A05  \
6                            0/0                          0/0   
7                            0/0                          0/0   
79                           0/0                          0/0   
80                           0/0                          0/0   
93                           0/0                          0/0   
..                           ...                          ...   
607                          0/0                          0/0   
608                          0/0                          0/0   
609                          0/0                          0/0   
610                          0/0                          0/0   
611                          0/0                          0/0   

    EvolvingFront_WGS_Plate3_A10 EvolvingFront_WGS_Plate3_B07  \
6                            0/0                          0/0   
7                            0/0                          0/0   
79                           1|1                          0/0   
80                           1|1                          0/0   
93                           0/0                          0/0   
..                           ...                          ...   
607                          0/0                          0/0   
608                          0/0                          0/0   
609                          0/0                          0/0   
610                          0/0                          0/0   
611                          0/0                          0/0   

    EvolvingFront_WGS_Plate3_D12 EvolvingFront_WGS_Plate4_B05  \
6                            0/0                          0/0   
7                            0/0                          0/0   
79                           0/0                          0/0   
80                           0/0                          0/0   
93                           1|1                          0/0   
..                           ...                          ...   
607                          0/0                          0/0   
608                          0/0                          0/0   
609                          0/0                          0/0   
610                          0/0                          0/0   
611                          0/0                          0/0   

    EvolvingFront_WGS_Plate4_D05 EvolvingFront_WGS_Plate5_A03  \
6                     

array([       9,        3,        3,     7655,    29602,      575,
              1,      266,    16320,     6497,    32428,    16155,
           4620,    10943,      591,    19024,    82124,  -203191,
          24372,    33316,    13640,    27587,    29152,    33750,
              8,    44410,    93786,     4545,    12952,    79151,
          10533,      338,     8701,    62555,    17189,      827,
             49,      221,    45600,    10586,    31616,    16968,
           4866,    59392,    21058,      686,    24601,    27365,
           7558,  -769044,     4954,    23211,     7344,    74694,
          31718,    15049,    51120,    28177,    38293,     3338,
            469,    31677,  -264958,    41589,     6416,    23973,
          76371,    12631,     2579,     7433,     8440,     1441,
           2389,    76149,   120355,    84980,     5627,     5204,
          44415,        1,    20218,     2197,     1096,     4800,
          56845,    10422,    33595,    42096,    12964,     6